config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  root 'store#index', as: 'store'

  resources :users
  resources :orders
  resources :line_items
  resources :cart
  resources :products

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  belongs_to :order

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  PAYMENT_TYPES = ["Check", "Credit card", "Purchase order"]
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  validates :title, :description, :price, presence: true

  private
    # Before deleting this product, make sure it's not referenced by a line item
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password
  after_destroy :ensure_an_admin_remains

  private
    def ensure_an_admin_remains
      if User.count.zero?
        raise "Can't delete last user"
      end
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authorize
  protect_from_forgery with: :exception

  protected
    def authorize
      unless User.find_by(id: session[:user_id])
        flash[:error] = "Please log in"
        redirect_to login_url
      end
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  skip_before_action :authorize, only: [:create, :update, :destroy]
  include CurrentCart
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  def index
  end

  def show
    @cart = Cart.find(params[:id])
  end

  def edit
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    flash[:success] = 'Your cart is currently empty'
    redirect_to store_url
  end

  private
    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      flash[:error] = 'Invalid cart'
      redirect_to store_url
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  skip_before_action :authorize, only: :create
  include CurrentCart
  before_action :set_cart, only: [:create]

  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)

    if @line_item.save
      flash[:message] = 'Item was successfully added.'
      redirect_to @line_item.cart
    else
      render action: 'new'
    end
  end

  def line_item_params
    params.require(:line_item).permit(:product_id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :authorize, only: [:new, :create]
  include CurrentCart
  before_action :set_cart, only: [:new, :create]

  def new
    if @cart.line_items.empty?
      flash[:error] = "Your cart is empty"
      redirect_to store_url
      return
    end
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)
    if @order.save
      Cart.destroy(session[:cart_id])
      session[:cart_id] = nil
      OrderNotifier.received(@order).deliver
      flash[:success] = "Thank you for your order"
      redirect_to store_url
    else
      render action: 'new'
    end
  end

  def index
    @orders = Order.all
    @products = Product.all
  end

  private
    def order_params
      params.require(:order).permit(:name, :address, :pay_type, :email)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to store_url
    else
      render 'new'
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id]).delete
    redirect_to store_url
  end

  private
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize
  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_url
    else
      flash[:alert] = "Invalid user/password combination"
      redirect_to login_url
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logged out"
    redirect_to store_url
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  skip_before_action :authorize
  def index
    @products = Product.order(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User successfully created"
      redirect_to users_url
    else
      render action: 'new'
    end
  end

  def update
    if @user.update(user_params)
      flash[:success] = "User successfully updated"
      redirect_to users_url
    else
      render action: 'edit'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    begin
      @user = User.find(params[:id])
      @user.destroy
      flash[:notice] = "User deleted"
    rescue StandardError => e
      flash[:notice] = e.message
    end
    redirect_to users_url
  end

  private
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart/edit.html.erb
<h1>Cart#edit</h1>
<p>Find me in app/views/cart/edit.html.erb</p>

app/views/cart/index.html.erb
<h1>Cart#index</h1>
<p>Find me in app/views/cart/index.html.erb</p>

app/views/cart/show.html.erb
<h2>Your Cart</h2>
<ul>
  <% @cart.line_items.each do |item| %>
  <li><%= item.quantity %> - <%= item.product.title %> - <%= number_to_currency(item.total_price) %></li>
  <% end %>
</ul>

<p>
  Total: <%= number_to_currency(@cart.total_price) %>
</p>
<%= button_to 'Checkout', new_order_path, method: :get %>
<%= button_to 'Empty cart', @cart, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/orders/index.html.erb
<h1>Orders</h1>
<%= pluralize(@orders.count, 'order') %><br><br>
<% @orders.each do |order| %>
  <%= order.name %><br>
  <%= order.address %><br>
  <% order.line_items.each do |item| %>
    <%= item.quantity %>x
    <%= @products.find(item.product_id).title %>
  <% end %>
<% end %>

app/views/orders/new.html.erb
<h1>Please enter your details</h1>

<%= form_for @order do |f| %>
  <% if @order.errors.any? %>
    <%= pluralize(@order.errors.count, 'error') %>
    <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :address %><br>
    <%= f.text_area :address, rows: 3, cols: 4 %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :pay_type %><br>
    <%= f.select :pay_type, Order::PAYMENT_TYPES, prompt: 'Select a payment method' %>
  </p>
  <p>
    <%= f.submit 'Place order' %>
  </p>
<% end %>

app/views/products/edit.html.erb
<h1>Edit product</h1>
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
    <%= pluralize(@product.errors.count, 'error') %>
    <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/products/index.html.erb
<h1>Ecommerce store</h1>
<p>
  <%= link_to 'Add a product', new_product_path %>
</p>

app/views/products/new.html.erb
<h1>Add a product</h1>
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
    <%= pluralize(@product.errors.count, 'error') %>
    <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/products/show.html.erb
<h4><%= @product.title %></h4>
<p>
  <%= @product.description %>
</p>
<p>
  <% if @product.image_url? %><%= @product.image_url %><% end %>
</p>
<p>
  <%= @product.price %>
</p>

app/views/users/edit.html.erb
<h1>Edit user</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, 'error') %>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :pasword %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/index.html.erb
<h1>All users</h1>
<% @users.each do |user| %>
  <%= user.name %><br>
  <%= link_to 'show', user %>
  <%= link_to 'edit', edit_user_path(user) %>
  <%= link_to 'delete', user, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/users/new.html.erb
<h1>Create a new user</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, 'error') %>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>