config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  root 'store#index', as: 'store'

  resources :users
  resources :orders
  resources :line_items
  resources :cart
  resources :products

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  belongs_to :order

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  PAYMENT_TYPES = ["Check", "Credit card", "Purchase order"]
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  validates :title, :description, :price, presence: true

  private
    # Before deleting this product, make sure it's not referenced by a line item
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password
  after_destroy :ensure_an_admin_remains

  private
    def ensure_an_admin_remains
      if User.count.zero?
        raise "Can't delete last user"
      end
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  skip_before_action :authorize, only: [:create, :update, :destroy]
  include CurrentCart
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  def index
  end

  def show
    @cart = Cart.find(params[:id])
  end

  def edit
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    flash[:success] = 'Your cart is currently empty'
    redirect_to store_url
  end

  private
    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      flash[:error] = 'Invalid cart'
      redirect_to store_url
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :authorize, only: [:new, :create]
  include CurrentCart
  before_action :set_cart, only: [:new, :create]

  def new
    if @cart.line_items.empty?
      flash[:error] = "Your cart is empty"
      redirect_to store_url
      return
    end
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)
    if @order.save
      Cart.destroy(session[:cart_id])
      session[:cart_id] = nil
      OrderNotifier.received(@order).deliver
      flash[:success] = "Thank you for your order"
      redirect_to store_url
    else
      render action: 'new'
    end
  end

  def index
    @orders = Order.all
    @products = Product.all
  end

  private
    def order_params
      params.require(:order).permit(:name, :address, :pay_type, :email)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to store_url
    else
      render 'new'
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id]).delete
    redirect_to store_url
  end

  private
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  skip_before_action :authorize
  def index
    @products = Product.order(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User successfully created"
      redirect_to users_url
    else
      render action: 'new'
    end
  end

  def update
    if @user.update(user_params)
      flash[:success] = "User successfully updated"
      redirect_to users_url
    else
      render action: 'edit'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    begin
      @user = User.find(params[:id])
      @user.destroy
      flash[:notice] = "User deleted"
    rescue StandardError => e
      flash[:notice] = e.message
    end
    redirect_to users_url
  end

  private
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>
<p>
  It's <%= Time.now %><br>
  We have <%= pluralize(@total_orders, "order") %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <nav>
      <ul>
        <li><%= link_to 'Home', store_path %></li>
        <% if session[:user_id] %>
          <li><%= link_to 'Orders', orders_path %></li>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Users', users_path %></li>
          <%= button_to 'Logout', logout_path, method: :delete %>
        <% end %>
      </ul>
    </nav>
  </header>
  <% flash.each do |message_type, message| %>
    <ul class="collection">
      <li class="collection-item"><%= message %></li>
    </ul>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/order_notifier/received.html.erb
<h1>OrderNotifier#received</h1>

<p>
  <%= @order.name %>, find me in app/views/order_notifier/received.html.erb
</p>

app/views/order_notifier/received.text.erb
OrderNotifier#received

<%= @order.name %>, find me in app/views/order_notifier/received.text.erb

app/views/order_notifier/shipped.html.erb
<h1>OrderNotifier#shipped</h1>

<p>
  <%= @order.namem %>, find me in app/views/order_notifier/shipped.html.erb
</p>

app/views/order_notifier/shipped.text.erb
OrderNotifier#shipped

<%= @order.name %>, find me in app/views/order_notifier/shipped.text.erb